@echo off
echo Starting Book Extractor Server...
IF NOT EXIST .venv (
    echo Creating virtual environment...
    python -m venv .venv
)
call .venv\Scripts\activate
echo Installing requirements...
pip install -r requirements.txt
echo Starting server...
uvicorn main:app --reload
pause
